#!/usr/bin/env python3

import os
import configparser
import binascii

# copy the config file from conf dir to either /etc/dnote or ~/.dnote,
# then run this script.

config = configparser.ConfigParser()

for path in ['/etc/dnote', '~/.dnote']:
    expanded_path = "{0}/{1}".format(os.path.expanduser(path), 'd-note.ini')
    if os.path.exists(expanded_path):
      try:
          f = open(expanded_path)
          #config.readfp(f)
          config.read_file(f)
          f.close()
      except configparser.InterpolationSyntaxError as e:
          raise EOFError("Unable to parse configuration file properly: {0}".format(e))

cfgs = {}

for section in config.sections():
    if section not in cfgs:
        cfgs[section] = {}

    for k, v in config.items(section):
        cfgs[section][k] = v

# make data_dir
data_dir = os.path.expanduser(cfgs['dnote']['data_dir'])

if not os.path.isdir(data_dir):
    os.mkdir(data_dir, int("0755"))

dconfig_path = os.path.expanduser(cfgs['dnote']['config_path'])
dconfig = dconfig_path + "/dconfig.py"

if not os.path.isdir(dconfig_path):
    os.mkdir(dconfig_path, int("0755"))

if not os.path.exists(dconfig):
    with open(dconfig, 'w') as f:
        f.write('aes_salt = "%s"\n' % binascii.hexlify(os.urandom(16)))
        f.write('mac_salt = "%s"\n' % binascii.hexlify(os.urandom(16)))
        f.write('nonce_salt = "%s"\n' % binascii.hexlify(os.urandom(16)))
        f.write('duress_salt = "%s"\n' % binascii.hexlify(os.urandom(16)))
    os.chmod(dconfig, int("0440"))
